name: "Build Ark Linux Release"

on:
    workflow_call:
      inputs:
        version:
          required: false
          description: "The Ark version"
          default: ${{ github.sha }}
          type: string
    workflow_dispatch:

jobs:
    license:
        name: Copy license and notice
        runs-on: ubuntu-latest
        steps:
            - name: Copy license and notice
              run: |
                  # Should happen only once to avoid cp errors in the matrix build
                  cp "$GITHUB_WORKSPACE/LICENSE" LICENSE
                  cp "$GITHUB_WORKSPACE/crates/ark/NOTICE" NOTICE

    build_linux:
        name: Build Linux
        runs-on: ubuntu-latest
        needs: license
        timeout-minutes: 60

        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DEBUG_FLAG: ${{ matrix.flavor == 'debug' && '-debug' || '' }}

        strategy:
            matrix:
                arch: [x64]
                flavor: [debug, release]

        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Setup Build Environment
              run: |
                  sudo apt-get update
                  sudo apt-get install -y cargo

            - name: Compile ARK (${{ matrix.flavor }})
              run: |
                  cargo clean
                  cargo build ${{ matrix.flavor == 'release' && '--release' || '' }}

            # Compress kernel to a zip file
            - name: Create archive
              run: |
                  # Enter the build directory
                  pushd target/${{ matrix.flavor }}

                  # Compress the kernel to an archive
                  ARCHIVE="$GITHUB_WORKSPACE/ark-${{ inputs.version }}-${{ matrix.flavor }}-linux-x64.zip"
                  zip -Xry $ARCHIVE ark LICENSE NOTICE

                  popd

            - name: Upload archive
              uses: actions/upload-artifact@v3
              with:
                  name: ark-${{ matrix.flavor }}-linux-x64-archive
                  path: ark-${{ inputs.version }}-${{ matrix.flavor }}-linux-x64.zip
